### ISSUE TITLE
How to use ponzu in existing application?

### ISSUE THREAD

**Issue by h7kanna** [ponzu-cms/ponzu#211] opened 2017-12-20 18:24 UTC
Hi, 
Thank you first, Ponzu is really nice.

I am trying to figure out how to add ponzu in a existing app that is built with github.com/labstack/echo router. I want to use existing middleware and reuse the existing routes along with ponzu generated API routes in a single server.

Is this kind of use case idiomatic with Ponzu? 

Any suggestions on adding ponzu into another application is appreciated.

Thanks.
Harsha

**Comment by nilslice** [comment] 2017-12-20 19:04
Hi @h7kanna - 

Thank you for the kind words, and welcome to Ponzu. I'm very happy that you're finding the project to be useful.

The use case you describe is fully idiomatic, and I have done this almost exact setup many times. If you'd like to keep your front-end and back-end code in separate repositories, then look into these projects:
https://github.com/nilslice/appfront (front end)
https://github.com/nilslice/appback (back end)

Notice how the Ponzu back-end imports the front-end as a package, and [attaches the router](https://github.com/nilslice/appback/blob/master/content/about.go#L54) to the `/` path, essentially mounting the router with your front-end logic to your Ponzu project. This does not need to be done within any particular content type file. You could add another file in the content package for your front-end code integration. The reason I would put it inside the content package somewhere is that it is auto-imported and thus wired up for you automatically. 

I would suggest also looking into using our official Go client for Ponzu, enabling easier use of the HTTP APIs provided by Ponzu. See an example in the `appfront` repo here: https://github.com/nilslice/appfront/blob/master/app.go#L28

I am thinking about ways to make this simpler. When I designed Ponzu, it was meant to be only an API backend and CMS, leaving the front-end 100% agnostic. But there have been quite a few users who've requested a solution to include a front-end as part of the Ponzu binary. 

Let me know if this helps or if you have other questions.

**Comment by h7kanna** [comment] 2017-12-20 22:55
Thanks @nilslice , I will refer the mentioned projects.

**Comment by h7kanna** [comment] 2017-12-21 04:41
Hi @nilslice ,
That worked. I could use echo router instead of gorilla mux as in appfront repo.
Here are few things.

-  I want to keep ponzu within the same repo. But
ponzu new github.com/h7kanna/myrepo fails with 'file already exists'.
It would be nice if it merges with existing directory. It can be dangerous though.

- How to pass configuration to the embedded router?
 ponzu run --config=config.yaml 
fails with invalid flags for my custom config. I am using  static config path as of now.

- I am doing this to cleanup router created resources in the init. This is only way as there are no custom lifecycle hooks.
```c := make(chan os.Signal, 1)
        signal.Notify(c, os.Interrupt)
	go func() {
		<-c
		router.Shutdown()
		os.Exit(0)
	}()
```

Thanks,
Harsha

**Comment by nilslice** [comment] 2017-12-21 05:06
@h7kanna - Glad it worked for you! To answer some of your other questions:

> I want to keep ponzu within the same repo. But ponzu new github.com/h7kanna/myrepo fails with 'file already exists'. It would be nice if it merges with existing directory. It can be dangerous though.

That's correct -- Ponzu initially warned you if you were about to overwrite any existing files, but we decided that there was a lot at risk if someone confirmed `yes` by mistake. Maybe there will be a `--force` flag at some point, since automated commands might suffer down the line. 

In order to put Ponzu inside your repo, you'd need to have it in a sub-directory, i.e. `github.com/h7kanna/myrepo/cms` or something. Or, just move the whole project into the repo after you have created a new Ponzu in another path on disk (I'd suggest not doing this as to avoid file / dir conflicts)

> How to pass configuration to the embedded router? `ponzu run --config=config.yaml` fails with invalid flags for my custom config. I am using static config path as of now.

There is currently no way to supply config at run-time. There was early support when we migrated to use `spf13/cobra` package instead of just `flag` from the standard library, but it was using `spf13/viper` which relied on so many dependencies, I didn't think it was a good long-term solution. I'd love to know if you have thoughts on this, and if it is something you'd consider contributing. 

You may be able to define the config path for your embedded router in code before run-time, using some of the router's own features (though I'm not very familiar with echo). 

> I am doing this to cleanup router created resources in the init. This is only way as there are no custom lifecycle hooks.

What are you shutting down? If you mount your router on the using the standard library http.Handler, then the server will be shut down when the process is terminated. Are you running your router on a different port? That would seem to defeat the purpose of bundling Ponzu with your existing application.

**Comment by h7kanna** [comment] 2017-12-21 05:23
Hi @nilslice ,

Thanks for quick answers. I will look into a good solution for custom config with minimal dependency. 
https://github.com/toml-lang/toml can be a candidate.
https://github.com/BurntSushi/toml

My router depends on services, logger, db objects etc. some of the I have to flush and clean on exit.

**Comment by nilslice** [comment] 2017-12-21 05:27
@h7kanna - shared feedback on what you find would be very helpful. Thanks for taking time to investigate. :+1: 

> My router depends on services, logger, db objects etc. some of the I have to flush and clean on exit.

That makes sense -- I appreciate the clarification. If you have thoughts or recommendations as to how a lifecycle hook manager could be introduced, it could be a beneficial feature to all Ponzu users. Your use case is certainly proof!

I am going to close this issue for now, but please feel free to comment here, or open more issues for other topics as you see fit.

**Closed by nilslice** 2017-12-21 05:27 UTC
